use_frameworks!

platform :ios, '9.0'

target 'HomePageCompon_Example' do
  pod 'HomePageCompon', :path => '../'

  target 'HomePageCompon_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
